### PR TITLE
Adding VirtualBox Guest Additions

### PR DESCRIPTION
**Pull request by nuxlli**
This change adds the installation of VirtualBox Guest Additions, the effect on debian2docker is therefore:
- Clock synchronization by VBoxService daemon;
- Supports mount of shared folders of VirtualBox `mount -t vbofs [name] [point]`;
- Automatically mount shared folders with '--automount`in`/ media / sf_`;
- Supports executing commands without ssh through `VBoxManage guestcontrol`;

As a positive side effect, I managed to reduce (at least in my tests), a 55MB image to 47MB.

### CODE REVIEW

**Comment by saitodisse** [comment]
:+1:

**Comment by gullitmiranda** [comment]
:+1:

**Comment by unclejack** [comment]
@nuxlli This PR makes some other changes as well. Those changes need to be discussed separately.

I'll focus on the vbox guest additions. We can do this, but only through multiple versions of the ISO. We need an ISO for vmware, one for hyper-v and one virtualbox if they all require custom guest additions. ISOs for the cloud using cloud init are also needed.

This means we're going to have at least 4 builds. I'm going to push some code changes soon to move this forward.

**Comment by unclejack** [comment]
@nuxlli I'm going to close this PR for now. The virtualbox tools and vmware tools will need to be included in separate builds.

**Pull request closed without merging**
